### ISSUE TITLE
How to add `jwt` / `session` auth to `configureAbly` request?

### ISSUE THREAD

**Issue by starlight-akouri** [ably-labs/react-hooks#43]
I am looking to secure the endpoint that issues my ably tokens. How is this done? 

I am using next-auth

**Comment by owenpearson** [comment]
Hey, @starlight-akouri, sorry for the late response on this one. It's quite hard to answer this generically since the best way to securely issue tokens to your client will depend on your specific requirements.

The easiest way is probably by [issuing ably tokens from the your auth endpoint](https://ably.com/docs/auth/token?lang=javascript#tokens) and using client options to send authentication details in the request to your auth server. If you need to write your own code to ensure that the request to your auth server is authenticated correctly, you can use the [`authCallback`](https://ably.com/docs/api/realtime-sdk/authentication?lang=javascript#auth-options) client option and make the http request yourself. I hope this helps, let me know if you have any further questions 🙂
